# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureConnectionType: 'ConnectedServiceNameARM'
    azureSubscription: 'dacpac_test'
    AuthenticationType: 'server'
    ServerName: 'DESKTOP-AT5KR48.fourier.co.za, 1433'
    deployType: 'DacpacTask'
    SqlUsername: 'Enrique'
    SqlPassword: 'Qwerty12'
    DeploymentAction: 'Publish'
    IpDetectionMethod: 'AutoDetect'
    DacpacFile: '$(Build.SourcesDirectory)\bin\Release\Automate DACPAC Deployment.dacpac'
    ConnectionString: 'Server=tcp:DESKTOP-AT5KR48.fourier.co.za, 1433; TrustServerCertificate=true; Encrypt=true;'
    AdditionalArguments: ' /TargetServerName:"DESKTOP-AT5KR48.fourier.co.za, 1433" /TargetDatabaseName= "PACDAC_TEST" /TargetUser:"Enrique" /TargetPassword:"Qwerty12"'
    

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

